model:
  policy_model:
    ckpt: t5-small
    input_padding_side: right
    train_generation_kwargs:
      do_sample: True
      top_k: 20
      top_p: null
      temperature: 0.7
    eval_generation_kwargs:
      do_sample: False
      num_beams: 1
  ref_policy:
    ckpt: t5-small
  
  
reward:
  factuality_model:
    ckpt: /cluster/project/sachan/sauc/MultiTask-CTG-NLF/tasks/qa_feedback/model_outputs/fact_rm
    batch_size: 8
    sample_interval: 500
    positive_reward: 0.5
    negative_reward: -0.5

env:
  max_input_len: 1024
  max_generated_len: 200
  nlf_cond: False
  num_quantiles: 5
  num_attributes: 1
  kl_coef: 0.05
  entropy_coef: 0.06

train:
  total_episodes: 80000
  sampling_batch_size_per_card: 1
  training_batch_size_per_card: 1
  lr: 0.00001
  n_warmup_steps: 100
  clip_grad: False
  max_grad_norm: 0.5
  seed: 42
  cuda_deterministic: True

data:
  train_data_path: /cluster/project/sachan/sauc/MultiTask-CTG-NLF/tasks/qa_feedback/data/train.json
  dev_data_path: /cluster/project/sachan/sauc/MultiTask-CTG-NLF/tasks/qa_feedback/data/dev.json
  test_data_path: /cluster/project/sachan/sauc/MultiTask-CTG-NLF/tasks/qa_feedback/data/test.json

logging:
  run_name: factuality_quark
  wandb_log: True
  wandb_entity: sauc-abadal
  wandb_project: sauc-ms-thesis
  log_interval: 100
  save_interval: 1000
  eval_interval: 500
  save_dir: /cluster/project/sachan/sauc/MultiTask-CTG-NLF/tasks/qa_feedback/model_outputs/factuality_quark