model:
  policy_model:
    base_model_ckpt: /cluster/project/sachan/sauc/MultiTask-CTG-NLF/tasks/qa_feedback/model_outputs/t5-large-1k-train
    model_checkpoint_ckpt: /cluster/project/sachan/sauc/MultiTask-CTG-NLF/tasks/qa_feedback/model_outputs/multitask_ctgnlf/sampling_two_best/12-08-2023_11:06:57/model/top_model_0_step_9500.pth
    input_padding_side: right
    eval_generation_kwargs:
      do_sample: False
      num_beams: 1

reward:
  batch_size: 8
  relevancy_model:
    ckpt: /cluster/project/sachan/sauc/MultiTask-CTG-NLF/tasks/qa_feedback/model_outputs/rel_rm
    positive_reward: 0.3
    negative_reward: -0.3
  factuality_model:
    ckpt: /cluster/project/sachan/sauc/MultiTask-CTG-NLF/tasks/qa_feedback/model_outputs/fact_rm
    positive_reward: 0.5
    negative_reward: -0.5
  completeness_model:
    ckpt: /cluster/project/sachan/sauc/MultiTask-CTG-NLF/tasks/qa_feedback/model_outputs/comp_rm
    mean: -0.44677690555995353
    std: 8.301160619054132
    bias: 0.0
    scale: 0.3

env:
  max_input_len: 1024
  max_generated_len: 200
  nlf_cond: True
  num_quantiles: 5
  num_attributes: 3

eval:
  sampling_batch_size_per_card: 8
  seed: 42
  cuda_deterministic: True

data:
  data_path: /cluster/project/sachan/sauc/MultiTask-CTG-NLF/tasks/qa_feedback/data/test.json

logging:
  save_dir: /cluster/project/sachan/sauc/MultiTask-CTG-NLF/tasks/qa_feedback/model_outputs/multitask_ctgnlf/sampling_two_best/12-08-2023_11:06:57